# docker-compose down && docker-compose build --no-cache && docker-compose up -d
services:
  agenda-manager-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: agenda-manager-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    restart: unless-stopped
    networks:
      - agenda-manager-api_agenda-net

networks:
  agenda-manager-api_agenda-net:
    external: true
