version: "3.8"

services:
  angular-app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    command: npm start

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - angular-app

  angular-app-prod:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    command: npm run build

  nginx-prod:
    image: nginx:alpine
    volumes:
      - ./docker/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - angular-app-prod
