version: "3.8"

services:
  agenda-manager-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: agenda-manager-web
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - agenda-network

networks:
  agenda-network:
    driver: bridge
