export const ApiUrls = {
  auth: {
    login: '/auth/login',
    refreshToken: '/auth/refresh-token',
  },
  accounts: {
    getAccountsPaginated: '/accounts/paginated',
    getAccountDetails: '/accounts/{userId}',
    createAccount: '/accounts',
    requestPasswordReset: '/accounts/request-password-reset',
    resendEmailConfirmation: '/accounts/resend-email-confirmation',
    confirmAccount: '/accounts/confirm-account',
    resetPassword: '/accounts/reset-password',
    verifyEmail: '/accounts/verify-email',
    updateAccount: '/accounts/{userId}',
    toggleIsActive: '/accounts/{userId}/toggle-is-active',
    confirmEmail: '/accounts/{userId}/confirm-email',
    toggleIsCollaborator: '/accounts/{userId}/toggle-is-collaborator',
  },
  calendars: {
    getCalendarsPaginated: '/calendars/paginated',
    getCalendarById: '/calendars/{calendarId}',
    getCalendarSettings: '/calendars/{calendarId}/settings',
    createCalendar: '/calendars',
    updateCalendar: '/calendars/{calendarId}',
    updateCalendarSettings: '/calendars/{calendarId}/settings',
    toggleIsActive: '/calendars/{calendarId}/toggle-is-active',
  },
  roles: {
    getRolesPaginated: '/roles/paginated',
    getAllRoles: '/roles',
    getRoleById: '/roles/{roleId}',
    getRolePermissionsById: '/roles/{roleId}/permissions',
    createRole: '/roles',
    updateRol: '/roles/{roleId}',
    updatePermissionForRole: '/roles/{roleId}/permissions/{permissionId}',
    deleteRole: '/roles/{roleId}',
  },
  userRoles: {
    getUsersByRoleIdPaginated: '/user-roles/{roleId}/users/paginated',
    getUsersNotInRoleIdPaginated: '/user-roles/{roleId}/exclude-users/paginated',
    getRolesByUserId: '/user-roles/{userId}/roles',
    getAvailableRolesByUserId: '/user-roles/{userId}/available-roles',
    assignUserToRole: '/user-roles/{roleId}/assign-user/{userId}',
    unAssignedUserFromRole: '/user-roles/{roleId}/unassigned-user/{userId}',
  },
} as const;
